name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_STONE_0F2EA1E0F }}
          action: 'upload'
          app_location: 'build' # Directory where static files are generated
          api_location: ''
        env:
          API_BASE_URL: 'https://white-stone-0f2ea1e0f.4.azurestaticapps.net'
          JWT_SECRET: '987089120938102uwoeifhjwoief098sdf09'
          SERVER_URL: 'https://grf-headless-fbeeesahfucac3a9.westus2-01.azurewebsites.net'
